# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BoardzillaDevtools < Formula
  desc ""
  homepage "https://docs.boardzilla.io/"
  version "0.2.2"
  license "GPL-v3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/boardzilla/boardzilla-devtools/releases/download/v0.2.2/bz_macos_arm64.tar.gz"
      sha256 "9ba7bd4000b1db1d01f993f4f39eeb56c7350de2e8cc4e6167ff09854307b804"

      def install
        bin.install "bz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boardzilla/boardzilla-devtools/releases/download/v0.2.2/bz_macos_amd64.tar.gz"
      sha256 "a4b4740ede97ad27e4094766ea67f0aac1e88a2dc1090d6f61dc40074cd02fd6"

      def install
        bin.install "bz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/boardzilla/boardzilla-devtools/releases/download/v0.2.2/bz_linux_amd64.tar.gz"
      sha256 "c1dc197714dcd02f4f1886e26970e7e719fa22f94f58265ea4e6f21db9fe8dbf"

      def install
        bin.install "bz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boardzilla/boardzilla-devtools/releases/download/v0.2.2/bz_linux_arm64.tar.gz"
      sha256 "5f8bc4da26eae275d9658d2cd19ad20b44b119217dec1570ab5705ab10281e8b"

      def install
        bin.install "bz"
      end
    end
  end
end
